name: web_tests_with_vscode
description: Examples of tests it'd be nice to run with VS code

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  meta: 1.2.3
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.6.0
  build_test: ^1.2.0
  build_web_compilers: ^2.12.0
  json_serializable: ^3.3.0
  test: ^1.15.7
  webdev: any
